cabal-version:      3.4

name:               ghengin-core
version:            0.1.0.0
tested-with:        GHC ==9.10.1
license:            BSD-3-Clause
license-file:       ../LICENSE
author:             romes
maintainer:         rodrigo.m.mesquita@gmail.com
category:           Graphics
build-type:         Simple
extra-doc-files:    ../CHANGELOG.md

flag dev
  default: True
  manual: True
  description: This flag controls development settings and should be manually disabled when the game is being built for release. The ghengin packaging tools will take care to set this flag to false when packaging.
               When enabled, vulkan validation layers are enabled.
               Run `cabal build -f-dev` to build with the flag disabled.
               -- Enable with -f+dev

common common-flags

  if flag(dev)
    ghc-options:
        -fno-ignore-asserts
        -- -dasm-lint
        -- -dcmm-lint
        -- -dstg-lint
        -- -g3
        -- -rtsopts -debug
        -- -fcheck-prim-bounds
        -- -fcmm-thread-sanitizer

    cpp-options:
        -DDEBUG
        -- -DDEBUG_TRACE
        -- -DTHINGS_ARE_GOING_THAT_BAD
        -- -DDEBUG_WRITE_SHADERS

  else
    ghc-options: -O2 -threaded
    cc-options: -O2

  ghc-options:
    -Wall
    -Wno-name-shadowing
    -Wno-partial-type-signatures

  default-extensions: UnicodeSyntax,
                      MultiParamTypeClasses,
                      NoStarIsType,
                      RankNTypes,
                      DataKinds,
                      PolyKinds,
                      GADTs,
                      ViewPatterns,
                      TypeApplications,
                      TypeFamilies,
                      ExplicitNamespaces,
                      TypeFamilyDependencies,
                      TypeOperators,
                      LambdaCase,
                      BlockArguments,
                      RecordWildCards,
                      UnboxedTuples,
                      PatternSynonyms,
                      DisambiguateRecordFields,
                      DeriveGeneric,
                      DerivingVia,
                      DerivingStrategies,
                      LinearTypes,
                      QualifiedDo,
                      QuantifiedConstraints,
                      RoleAnnotations,
                      PostfixOperators,
                      ImportQualifiedPost,

                      -- Use Ghengin.Core.Prelude!
                      NoImplicitPrelude,

  default-language: GHC2021

library
    import:           common-flags

    exposed-modules:  Ghengin.Core,
                      Ghengin.Core.Input,

                      Ghengin.Core.Material,
                      Ghengin.Core.Mesh,

                      Ghengin.Core.Render.Pipeline,
                      Ghengin.Core.Render.Property,
                      Ghengin.Core.Render.Packet,
                      Ghengin.Core.Render.Queue,
                      Ghengin.Core.Render

    -- FIR re-exports, so people can import FIR without depending on fir (it's
    -- already a transitive dependency, we simply make it easier to access)
    reexported-modules: FIR, Math.Linear, Math.Quaternion,
                        -- generics-sop, for deriving generically
                        Generics.SOP

    -- Re-export vulkan renderer backend
    -- These used to be backpack signatures, but we killed backpack...
    -- The vulkan backend is kept in a separate package and should be independent.
    -- Ideally, ghengin-core wouldn't have to ever depend on vulkan directly
    -- since the renderer should be a complete abstraction.
    --
    -- The re-exports make it possible to manipulate renderer data etc
    reexported-modules: Ghengin.Vulkan.Renderer,
                        Ghengin.Vulkan.Renderer.Kernel,
                        Ghengin.Vulkan.Renderer.DescriptorSet,
                        Ghengin.Vulkan.Renderer.Buffer,
                        Ghengin.Vulkan.Renderer.Pipeline,
                        Ghengin.Vulkan.Renderer.Texture,
                        Ghengin.Vulkan.Renderer.Sampler,
                        Ghengin.Vulkan.Renderer.Command

    -- Re-export modules that are part of ghengin-core-indep (see also #23322)
    -- Keep these modules in sync with the exported modules from ghengin-core-indep!
    reexported-modules: Ghengin.Core.Mesh.Vertex,

                        Ghengin.Core.Type.Compatible,
                        Ghengin.Core.Type.Compatible.Pixel,
                        Ghengin.Core.Type.Utils,

                        Ghengin.Core.Shader,
                        Ghengin.Core.Shader.Data,
                        Ghengin.Core.Shader.Pipeline,

                        Ghengin.Core.Prelude,
                        Ghengin.Core.Log,

    hs-source-dirs:   ghengin-core

    build-depends:    base >= 4.20, ghc >= 9.10,
                      fir,

                      -- TODO: NOT DEPEND ON VULKAN IN CORE.
                      -- EVEN THOUGH WE NO LONGER USE BACKPACK, WE STILL WANT CLEAN SEPARATION OF CONCERNS.
                      vulkan >= 3.26.2,
                      linear-base >= 0.4.0,
                      reference-counting >= 0.2.0.0,
                      os-string,
                      text >= 0.2,
                      temporary,

                      template-haskell,
                      stm, async,
                      containers,
                      mtl,
                      vector >= 0.13,
                      generics-sop,

                      gl-block,

                      -- ghengin-core:vulkan should give everything that's
                      -- necessary to work with the renderer without having to
                      -- import vulkan directly.
                      ghengin-core:vulkan,
                      ghengin-core:backend-independent-bits,
                      linear-utils,
                      ptrdiff,
                      constraints,
                      finite-typelits,

                      -- we use this for now directly in some hacky bits...
                      GLFW-b,

                      -- For textures
                      JuicyPixels,

                      -- force this indirect dependency's version
                      ghc-tcplugins-extra >= 0.4.6

library backend-independent-bits
    import:           common-flags

    visibility:       public

    exposed-modules:  Ghengin.Core.Mesh.Vertex,

                      Ghengin.Core.Type.Compatible,
                      Ghengin.Core.Type.Compatible.Pixel,
                      Ghengin.Core.Type.Utils,

                      Ghengin.Core.Shader,
                      Ghengin.Core.Shader.Data,
                      Ghengin.Core.Shader.Pipeline,

                      Ghengin.Core.Prelude,
                      Ghengin.Core.Log,

    hs-source-dirs:   ghengin-core-indep

    build-depends:    base,
                      fir,
                      -- TODO: NOT DEPEND ON VULKAN IN CORE INDEP
                      vulkan,
                      linear-base,
                      reference-counting >= 0.2.0.0,

                      template-haskell,
                      containers,
                      vector,
                      bytestring,

                      fast-logger,

                      gl-block,
                      geomancy,
                      constraints,
                      ptrdiff,
                      generics-sop,
                      finite-typelits,

                      -- CompatiblePixel
                      JuicyPixels,

                      linear-utils

--------------------------------------------------------------------------------
-- Backend implementations (Vulkan, for now that's all...)
--------------------------------------------------------------------------------

library vulkan
    import:           common-flags

    visibility:       public

    exposed-modules:  Ghengin.Vulkan.Renderer.Kernel,
                      Ghengin.Vulkan.Renderer.DescriptorSet,
                      Ghengin.Vulkan.Renderer.Buffer,
                      Ghengin.Vulkan.Renderer.Pipeline,
                      Ghengin.Vulkan.Renderer.Texture,

                      Ghengin.Vulkan.Renderer,

                      Ghengin.Vulkan.Renderer.ImmediateSubmit,
                      Ghengin.Vulkan.Renderer.Image,
                      Ghengin.Vulkan.Renderer.Sampler,

                      -- Should soon enough be part of the required pieces
                      Ghengin.Vulkan.Renderer.Command,
                      -- Modules that don't instance signatures
                      Ghengin.Vulkan.Renderer.GLFW.Window,
                      Ghengin.Vulkan.Renderer.Synchronization,

                      Ghengin.Vulkan.Renderer.Context,
                      Ghengin.Vulkan.Renderer.Context.Instance,
                      Ghengin.Vulkan.Renderer.Context.Device,
                      Ghengin.Vulkan.Renderer.Context.Device.Physical,
                      Ghengin.Vulkan.Renderer.Context.Swapchain,

                      -- Vulkan x FIR --
                      ------------------
                      -- Modules adapted from FIR's excellent fir-examples/src/Vulkan
                      -- which have vulkan abstractions shared between us and FIR.
                      FIR.Vulkan.Pipeline,
                      FIR.Vulkan.Formats,
                      FIR.Vulkan.Memory,
                      FIR.Vulkan.Attachment
                      -- FIR.Vulkan.Resource

    hs-source-dirs:   ghengin-vulkan

    build-depends:    base,
                      fir,
                      vulkan,
                      text-short,
                      GLFW-b,
                      linear-base,
                      reference-counting >= 0.2.0.0,
                      ghengin-core:backend-independent-bits,
                      gl-block,
                      temporary,
                      finite-typelits,

                      -- For textures
                      JuicyPixels,

                      containers,
                      filepath,
                      bytestring,
                      mtl,
                      vector,
                      linear-utils,
                      ptrdiff
